### ISSUE TITLE
Please refer to the website "https://aktu.ac.in/" and add the "Program Details" section.

### ISSUE THREAD

**Issue by utkarshsingx** [utkarshsingx/aktu.ac.in#2]
Add html and css code for it. For images just copy the image link address and use it as img src

**Comment by 08Uzair** [comment]
Please Assign this to me

**Comment by 08Uzair** [comment]
i will complete this work in 1-2hrs

**Comment by utkarshsingx** [comment]
I've assigned this issue for you.

**Comment by 08Uzair** [comment]
Should i create a new page for Program Details or should it be on the same home page . If it should be on same home page then below which section

**Comment by utkarshsingx** [comment]
Add Program Details in the same new page. No need to create new page. Just create new page-2 div  inside body div and below page-1 div @08Uzair

**Comment by 08Uzair** [comment]
[utkarshsingx](https://github.com/utkarshsingx) I had made the PR Please check it and please give me the review of my work done on your project 
Thank You

**Comment by utkarshsingx** [comment]
Well done @08Uzair. Your contribution will be counted in hacktoberfest accepted PR. Keep it up :)
