### ISSUE TITLE
Add the favicon to the website.

### ISSUE THREAD

**Issue by utkarshsingx** [utkarshsingx/aktu.ac.in#3]
Please refer to the website "https://aktu.ac.in/"

**Comment by mohdimran25** [comment]
hi @utkarshsingx, assign it to me.

**Comment by utkarshsingx** [comment]
I've assigned this issue to you @mohdimran25

**Comment by Bhavya-Chawla** [comment]
Your project looks interesting and innovative , I would really like to work on it.
Can you please assign me this issue?

**Comment by utkarshsingx** [comment]
Sure you can work on it. @Bhavya-Chawla. I've assigned this issue to you.

**Comment by Bhavya-Chawla** [comment]
I've initiated PR #10 . Please have a look.

**Comment by utkarshsingx** [comment]
Great! Keep it up:)
