### ISSUE TITLE
Add media gallary and college event page. 

### ISSUE THREAD

**Issue by utkarshsingx** [utkarshsingx/aktu.ac.in#6]
Add media gallary section that also includes college events option.

<img width="1440" alt="media gallary" src="https://github.com/utkarshsingx/aktu.ac.in/assets/92610758/28ff39fc-91b6-4584-8ee0-5aa18e912606">

**Make a new branch to for pull request. And add a screenshot of your work.** 

Take help from official website that is cloned : [https://aktu.ac.in/](url)

**Comment by LalitDeore** [comment]
Hey @utkarshsingx assign this task to me will do this

**Comment by utkarshsingx** [comment]
I've assigned this issue @LalitDeore

**Comment by utkarshsingx** [comment]
contributed under #13
