### ISSUE TITLE
Add our websites section. 

### ISSUE THREAD

**Issue by utkarshsingx** [utkarshsingx/aktu.ac.in#8]
Add Our websites section that includes images as shown.

<img width="1439" alt="our websites" src="https://github.com/utkarshsingx/aktu.ac.in/assets/92610758/407194be-1fcb-4644-9513-a2f84130429d">

**Make a new branch to for pull request. And add a screenshot of your work.** 

Take help from official website that is cloned : [https://aktu.ac.in/](url)

**Comment by LalitDeore** [comment]
can you assign this task to me?

**Comment by utkarshsingx** [comment]
Ok I have assigned this to you. Goodluck!!

**Comment by utkarshsingx** [comment]
completed under commit #12 .
